// Code generated by "stringer --type TokenType"; DO NOT EDIT.

package olex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokUnknown-0]
	_ = x[TokWhiteSpace-1]
	_ = x[TokString-2]
	_ = x[TokNumber-3]
	_ = x[TokIdentifier-4]
	_ = x[TokOther-5]
	_ = x[TokEnd-6]
	_ = x[TokError-7]
}

const _TokenType_name = "TokUnknownTokWhiteSpaceTokStringTokNumberTokIdentifierTokOtherTokEndTokError"

var _TokenType_index = [...]uint8{0, 10, 23, 32, 41, 54, 62, 68, 76}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
