package main

import (
	"reflect"

	. "github.com/spearson78/go-optic"
	"github.com/spearson78/go-optic/expr"
	goscript "github.com/spearson78/go-script"
)

func init() {
	pkg := goscript.Package{
		Name: "github.com/spearson78/go-optic",
		Exported: map[string]reflect.Value{
			//Hand crafted
			"FieldLens": reflect.ValueOf(fieldLens),
			"DownCast":  reflect.ValueOf(goscript.GenericFunction(downCast)),
			"DownCastP": reflect.ValueOf(goscript.GenericFunction(downCast)),

			"OrderBy":  reflect.ValueOf(goscript.GenericFunction(orderBy)),
			"OrderByI": reflect.ValueOf(goscript.GenericFunction(orderByI)),
			"IxMapIso": reflect.ValueOf(ixMapIso),
			"MaxOf":    reflect.ValueOf(goscript.GenericFunction(maxOf)),
			"MinOf":    reflect.ValueOf(goscript.GenericFunction(minOf)),

			//listfncs
			//action_combinators.go
			"AsModify":     reflect.ValueOf(AsModify[any, any, any, any, any, any, any, any, any, any, any]),
			"AsModifyI":    reflect.ValueOf(AsModifyI[any, any, any, any, any, any, any, any, any, any, any]),
			"AsSet":        reflect.ValueOf(AsSet[any, any, any, any, any, any, any, any, any, any, any]),
			"AsReverseGet": reflect.ValueOf(AsReverseGet[any, any, any, any, any, any, any, any, any]),
			// actions.go
			"Get":                reflect.ValueOf(Get[any, any, any, any, any, any, any, any, any]),
			"GetContext":         reflect.ValueOf(GetContext[any, any, any, any, any, any, any, any, any]),
			"MustGet":            reflect.ValueOf(MustGet[any, any, any, any, any, any, any, any, any]),
			"ReverseGet":         reflect.ValueOf(ReverseGet[any, any, any, any, any, any, any, any, any]),
			"ReverseGetContext":  reflect.ValueOf(ReverseGetContext[any, any, any, any, any, any, any, any, any]),
			"MustReverseGet":     reflect.ValueOf(MustReverseGet[any, any, any, any, any, any, any, any, any]),
			"Modify":             reflect.ValueOf(Modify[any, any, any, any, any, any, any, any, any, any, any]),
			"ModifyContext":      reflect.ValueOf(ModifyContext[any, any, any, any, any, any, any, any, any, any, any]),
			"MustModify":         reflect.ValueOf(MustModify[any, any, any, any, any, any, any, any, any, any, any]),
			"ModifyCheck":        reflect.ValueOf(ModifyCheck[any, any, any, any, any, any, any, any, any, any, any]),
			"ModifyCheckContext": reflect.ValueOf(ModifyCheckContext[any, any, any, any, any, any, any, any, any, any, any]),
			"MustModifyCheck":    reflect.ValueOf(MustModifyCheck[any, any, any, any, any, any, any, any, any, any, any]),
			"GetFirst":           reflect.ValueOf(GetFirst[any, any, any, any, any, any, any, any, any]),
			"GetFirstContext":    reflect.ValueOf(GetFirstContext[any, any, any, any, any, any, any, any, any]),
			"MustGetFirst":       reflect.ValueOf(MustGetFirst[any, any, any, any, any, any, any, any, any]),
			"Set":                reflect.ValueOf(Set[any, any, any, any, any, any, any, any, any]),
			"SetContext":         reflect.ValueOf(SetContext[any, any, any, any, any, any, any, any, any]),
			"MustSet":            reflect.ValueOf(MustSet[any, any, any, any, any, any, any, any, any]),
			// actions_indexed.go
			"GetI":                reflect.ValueOf(GetI[any, any, any, any, any, any, any]),
			"GetContextI":         reflect.ValueOf(GetContextI[any, any, any, any, any, any, any]),
			"MustGetI":            reflect.ValueOf(MustGetI[any, any, any, any, any, any, any]),
			"ModifyI":             reflect.ValueOf(ModifyI[any, any, any, any, any, any, any, any, any, any, any]),
			"ModifyContextI":      reflect.ValueOf(ModifyContextI[any, any, any, any, any, any, any, any, any, any, any]),
			"MustModifyI":         reflect.ValueOf(MustModifyI[any, any, any, any, any, any, any, any, any, any, any]),
			"ModifyCheckI":        reflect.ValueOf(ModifyCheckI[any, any, any, any, any, any, any, any, any, any, any]),
			"ModifyCheckContextI": reflect.ValueOf(ModifyCheckContextI[any, any, any, any, any, any, any, any, any, any, any]),
			"MustModifyCheckI":    reflect.ValueOf(MustModifyCheckI[any, any, any, any, any, any, any, any, any, any, any]),
			"GetFirstI":           reflect.ValueOf(GetFirstI[any, any, any, any, any, any, any, any, any]),
			"GetFirstContextI":    reflect.ValueOf(GetFirstContextI[any, any, any, any, any, any, any, any, any]),
			"MustGetFirstI":       reflect.ValueOf(MustGetFirstI[any, any, any, any, any, any, any, any, any]),
			// applicative.go
			"WithLogging":       reflect.ValueOf(WithLogging[any, any, any, any, any, any, any, any, any]),
			"WithOption":        reflect.ValueOf(WithOption[any, any, any, any, any, any, any, any, any]),
			"WithFunc":          reflect.ValueOf(WithFunc[any, any, any, any, any, any, any, any, any, any]),
			"WithComprehension": reflect.ValueOf(WithComprehension[any, any, any, any, any, any, any, any, any]),
			"WithEither":        reflect.ValueOf(WithEither[any, any, any, any, any, any, any, any, any, any]),
			"WithValidation":    reflect.ValueOf(WithValidation[any, any, any, any, any, any, any, any, any, any]),
			// bitwise.go
			"BitAndT2": reflect.ValueOf(BitAndT2[int]),
			"BitAnd":   reflect.ValueOf(BitAnd[int]),
			"BitOrT2":  reflect.ValueOf(BitOrT2[int]),
			"BitOr":    reflect.ValueOf(BitOr[int]),
			"BitXorT2": reflect.ValueOf(BitXorT2[int]),
			"BitXor":   reflect.ValueOf(BitXor[int]),
			"BitNot":   reflect.ValueOf(BitNot[int]),
			// cast.go
			//DownCast needs special handling to preserve it's prism behavior.
			//THese casts effectively become casts from any to any. The coercion of values will change them to the correct type on demand.
			"UpCast":    reflect.ValueOf(UpCast[any, any]),
			"IsoCast":   reflect.ValueOf(IsoCast[any, any]),
			"IsoCastP":  reflect.ValueOf(IsoCastP[any, any, any, any]),
			"IsoCastE":  reflect.ValueOf(IsoCastE[any, any]),
			"IsoCastEP": reflect.ValueOf(IsoCastEP[any, any, any, any]),
			// collection.go
			"Col":                reflect.ValueOf(Col[any]),
			"ColE":               reflect.ValueOf(ColE[any]),
			"ColI":               reflect.ValueOf(ColI[any, any]),
			"ColIE":              reflect.ValueOf(ColIE[any, any, any]),
			"EqCol":              reflect.ValueOf(EqCol[any, any, any, any]),
			"EqColT2":            reflect.ValueOf(EqColT2[any, any, any, any]),
			"EqColT2I":           reflect.ValueOf(EqColT2I[any, any, any, any, any]),
			"EqT2Of":             reflect.ValueOf(EqT2Of[any, any, any, any, any, any, any, any]),
			"ColSourceFocusPure": reflect.ValueOf(ColSourceFocusPure[any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"ColSourceFocusErr":  reflect.ValueOf(ColSourceFocusErr[any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"ColSourcePure":      reflect.ValueOf(ColSourcePure[any, any, any, any, any, any, any, any, any, any, any]),
			"ColSourceErr":       reflect.ValueOf(ColSourceErr[any, any, any, any, any, any, any, any, any, any, any, any]),
			"ColFocusPure":       reflect.ValueOf(ColFocusPure[any, any, any, any, any, any, any, any, any, any, any, any]),
			"ColFocusErr":        reflect.ValueOf(ColFocusErr[any, any, any, any, any, any, any, any, any, any, any, any]),
			"ColPure":            reflect.ValueOf(ColPure[any, any, any]),
			"ColErr":             reflect.ValueOf(ColErr[any, any, any]),
			"ValCol":             reflect.ValueOf(ValCol[any]),
			"ValColI":            reflect.ValueOf(ValColI[any, any]),
			"ValColE":            reflect.ValueOf(ValColE[any]),
			"ValColIE":           reflect.ValueOf(ValColIE[any, any, any]),
			"RangeCol":           reflect.ValueOf(RangeCol[int]),
			"TraverseCol":        reflect.ValueOf(TraverseCol[any, any]),
			"TraverseColI":       reflect.ValueOf(TraverseColI[any, any]),
			"TraverseColIE":      reflect.ValueOf(TraverseColIE[any, any, any]),
			"TraverseColE":       reflect.ValueOf(TraverseColE[any, any, any]),
			"TraverseColP":       reflect.ValueOf(TraverseColP[any, any, any]),
			"TraverseColEP":      reflect.ValueOf(TraverseColEP[any, any, any, any]),
			"TraverseColIEP":     reflect.ValueOf(TraverseColIEP[any, any, any, any]),
			"ColOf":              reflect.ValueOf(ColOf[any, any, any, any, any, any, any, any]),
			"ColOfP":             reflect.ValueOf(ColOfP[any, any, any, any, any, any, any, any, any]),
			// collection_op.go
			"ReversedCol":    reflect.ValueOf(ReversedCol[any, any]),
			"ReversedColP":   reflect.ValueOf(ReversedColP[any, any, any]),
			"FilteredCol":    reflect.ValueOf(FilteredCol[any, any, any]),
			"FilteredColI":   reflect.ValueOf(FilteredColI[any, any, any]),
			"Append":         reflect.ValueOf(Append[any]),
			"AppendCol":      reflect.ValueOf(AppendCol[any, any, any]),
			"PrependCol":     reflect.ValueOf(PrependCol[any, any, any]),
			"Prepend":        reflect.ValueOf(Prepend[any]),
			"OrderedCol":     reflect.ValueOf(OrderedCol[any, any, any]),
			"OrderedColI":    reflect.ValueOf(OrderedColI[any, any, any]),
			"SubCol":         reflect.ValueOf(SubCol[any, any]),
			"ReIndexedCol":   reflect.ValueOf(ReIndexedCol[any, any, any, any, any, any, any, any]),
			"ReIndexedColI":  reflect.ValueOf(ReIndexedColI[any, any, any, any, any, any, any, any, any, any]),
			"ReIndexedColP":  reflect.ValueOf(ReIndexedColP[any, any, any, any, any, any, any, any, any]),
			"ReIndexedColIP": reflect.ValueOf(ReIndexedColIP[any, any, any, any, any, any, any, any, any, any, any]),
			// collection_type.go
			"ColType":         reflect.ValueOf(ColType[any, any, any, any, any, any, any, any, any, any]),
			"ColTypeP":        reflect.ValueOf(ColTypeP[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"TraverseColType": reflect.ValueOf(TraverseColType[any, any, any, any, any, any]),
			"ColTypeToCol":    reflect.ValueOf(ColTypeToCol[any, any, any, any, any, any]),
			"ColToColType":    reflect.ValueOf(ColToColType[any, any, any, any, any, any]),
			"ColTypeOf":       reflect.ValueOf(ColTypeOf[any, any, any, any, any, any, any, any, any, any]),
			"ColTypeOfP":      reflect.ValueOf(ColTypeOfP[any, any, any, any, any, any, any, any, any, any, any]),
			// combinator.go
			"CombiRw":                reflect.ValueOf(CombiRw[any, any, any, any, any, any, any, any, any, any]),
			"CombiDir":               reflect.ValueOf(CombiDir[any, any, any, any, any, any, any, any, any, any]),
			"CombiEErr":              reflect.ValueOf(CombiEErr[any, any, any, any, any, any, any, any, any, any]),
			"CombiColTypeErr":        reflect.ValueOf(CombiColTypeErr[any, any, any, any, any, any, any]),
			"CombiColFocusErr":       reflect.ValueOf(CombiColFocusErr[any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"CombiColSourceErr":      reflect.ValueOf(CombiColSourceErr[any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"CombiColSourceFocusErr": reflect.ValueOf(CombiColSourceFocusErr[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"CombiTraversal":         reflect.ValueOf(CombiTraversal[any, any, any, any, any, any, any, any]),
			"CombiLens":              reflect.ValueOf(CombiLens[any, any, any, any, any, any, any]),
			"CombiGetMod":            reflect.ValueOf(CombiGetMod[any, any, any, any, any, any, any]),
			"CombiIsoMod":            reflect.ValueOf(CombiIsoMod[any, any, any, any, any, any, any, any]),
			"CombiGetter":            reflect.ValueOf(CombiGetter[any, any, any, any, any, any]),
			"CombiPrism":             reflect.ValueOf(CombiPrism[any, any, any, any, any, any, any, any]),
			"CombiIteration":         reflect.ValueOf(CombiIteration[any, any, any, any, any, any, any]),
			"CombiIso":               reflect.ValueOf(CombiIso[any, any, any, any, any, any, any]),
			// combinators.go
			"Length":         reflect.ValueOf(Length[any, any, any, any, any, any, any, any, any]),
			"Taking":         reflect.ValueOf(Taking[any, any, any, any, any, any, any, any]),
			"Dropping":       reflect.ValueOf(Dropping[any, any, any, any, any, any, any, any]),
			"Reversed":       reflect.ValueOf(Reversed[any, any, any, any, any, any, any, any, any]),
			"TakingWhile":    reflect.ValueOf(TakingWhile[any, any, any, any, any, any, any, any, any]),
			"DroppingWhile":  reflect.ValueOf(DroppingWhile[any, any, any, any, any, any, any, any, any]),
			"TrimmingWhile":  reflect.ValueOf(TrimmingWhile[any, any, any, any, any, any, any, any, any]),
			"Filtered":       reflect.ValueOf(Filtered[any, any, any, any, any, any, any, any, any]),
			"FilteredP":      reflect.ValueOf(FilteredP[any, any, any, any, any, any, any, any, any, any]),
			"Element":        reflect.ValueOf(Element[any, any, any, any, any, any, any, any]),
			"Coalesce":       reflect.ValueOf(Coalesce[any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Coalesce3":      reflect.ValueOf(Coalesce3[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Coalesce4":      reflect.ValueOf(Coalesce4[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"CoalesceN":      reflect.ValueOf(CoalesceN[any, any, any, any, any, any, any, any, any]),
			"Embed":          reflect.ValueOf(Embed[any, any, any, any, any, any, any, any, any]),
			"Ignore":         reflect.ValueOf(Ignore[any, any, any, any, any, any, any, any]),
			"Stop":           reflect.ValueOf(Stop[any, any, any, any, any, any, any, any]),
			"Catch":          reflect.ValueOf(Catch[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"CatchP":         reflect.ValueOf(CatchP[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Reduce":         reflect.ValueOf(Reduce[any, any, any, any, any, any, any, any, any, any, any, any]),
			"MapReduce":      reflect.ValueOf(MapReduce[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"First":          reflect.ValueOf(First[any, any, any, any, any, any, any, any]),
			"FirstOrDefault": reflect.ValueOf(FirstOrDefault[any, any, any, any, any, any, any, any]),
			"FirstOrError":   reflect.ValueOf(FirstOrError[any, any, any, any, any, any, any]),
			"Last":           reflect.ValueOf(Last[any, any, any, any, any, any, any, any]),
			"Ordered":        reflect.ValueOf(Ordered[any, any, any, any, any, any, any, any, any, any]),
			"Matching":       reflect.ValueOf(Matching[any, any, any, any, any, any, any, any, any]),
			"ForEach":        reflect.ValueOf(ForEach[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Polymorphic":    reflect.ValueOf(Polymorphic[any, any, any, any, any, any, any, any, any, any, any]),
			"EditDistance":   reflect.ValueOf(EditDistance[any, any, any, any, any, any, any, any, any, any]),
			"Concat":         reflect.ValueOf(Concat[any, any, any, any, any, any, any, any, any, any, any]),
			"Concat3":        reflect.ValueOf(Concat3[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Concat4":        reflect.ValueOf(Concat4[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"ConcatN":        reflect.ValueOf(ConcatN[any, any, any, any, any, any, any]),
			"Grouped":        reflect.ValueOf(Grouped[any, any, any, any, any, any, any, any, any, any, any, any]),
			"Prefixed":       reflect.ValueOf(Prefixed[any, any, any, any, any, any, any, any, any]),
			// combinators_indexed.go
			"TakingWhileI":    reflect.ValueOf(TakingWhileI[any, any, any, any, any, any, any, any, any]),
			"DroppingWhileI":  reflect.ValueOf(DroppingWhileI[any, any, any, any, any, any, any, any, any]),
			"TrimmingWhileI":  reflect.ValueOf(TrimmingWhileI[any, any, any, any, any, any, any, any, any]),
			"FilteredI":       reflect.ValueOf(FilteredI[any, any, any, any, any, any, any, any, any]),
			"FilteredIP":      reflect.ValueOf(FilteredIP[any, any, any, any, any, any, any, any, any, any]),
			"Index":           reflect.ValueOf(Index[any, any, any, any, any, any, any, any]),
			"Lookup":          reflect.ValueOf(Lookup[any, any, any, any, any, any, any, any, any]),
			"WithIndex":       reflect.ValueOf(WithIndex[any, any, any, any, any, any, any, any, any]),
			"Indices":         reflect.ValueOf(Indices[any, any, any, any, any, any, any, any, any]),
			"Indexing":        reflect.ValueOf(Indexing[any, any, any, any, any, any, any, any, any]),
			"ReIndexed":       reflect.ValueOf(ReIndexed[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"SelfIndex":       reflect.ValueOf(SelfIndex[any, any, any, any, any, any, any, any, any, any]),
			"OrderedI":        reflect.ValueOf(OrderedI[any, any, any, any, any, any, any, any, any, any]),
			"FirstOrDefaultI": reflect.ValueOf(FirstOrDefaultI[any, any, any, any, any, any, any, any]),
			"ForEachI":        reflect.ValueOf(ForEachI[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"EditDistanceI":   reflect.ValueOf(EditDistanceI[any, any, any, any, any, any, any, any, any, any, any]),
			// compose.go
			"Compose":     reflect.ValueOf(Compose[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"ComposeLeft": reflect.ValueOf(ComposeLeft[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"ComposeBoth": reflect.ValueOf(ComposeBoth[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"ComposeI":    reflect.ValueOf(ComposeI[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"JoinCtxErr":  reflect.ValueOf(JoinCtxErr),
			//TODO: these probably need the same treatment as IxMapIso
			"IxMap":      reflect.ValueOf(IxMap[any, any, any]),
			"IxMapLeft":  reflect.ValueOf(IxMapLeft[any, any]),
			"IxMapRight": reflect.ValueOf(IxMapRight[any, any]),
			"IxMapBoth":  reflect.ValueOf(IxMapBoth[any, any]),
			// compose_generated.go
			"Compose3":  reflect.ValueOf(Compose3[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Compose4":  reflect.ValueOf(Compose4[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Compose5":  reflect.ValueOf(Compose5[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Compose6":  reflect.ValueOf(Compose6[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Compose7":  reflect.ValueOf(Compose7[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Compose8":  reflect.ValueOf(Compose8[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Compose9":  reflect.ValueOf(Compose9[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Compose10": reflect.ValueOf(Compose10[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			// diff.go
			"Distance":         reflect.ValueOf(Distance[any]),
			"DistanceI":        reflect.ValueOf(DistanceI[any, any]),
			"DistanceE":        reflect.ValueOf(DistanceE[any, any]),
			"DistanceIE":       reflect.ValueOf(DistanceIE[any, any]),
			"DistancePercent":  reflect.ValueOf(DistancePercent[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"DistancePercentI": reflect.ValueOf(DistancePercentI[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"DiffColT2I":       reflect.ValueOf(DiffColT2I[any, any, any, any, any]),
			"DiffColT2":        reflect.ValueOf(DiffColT2[any, any, any, any, any]),
			// either.go
			"Chosen":       reflect.ValueOf(Chosen[any]),
			"Left":         reflect.ValueOf(Left[any, any]),
			"LeftP":        reflect.ValueOf(LeftP[any, any, any]),
			"Right":        reflect.ValueOf(Right[any, any]),
			"RightP":       reflect.ValueOf(RightP[any, any, any]),
			"BesideEither": reflect.ValueOf(BesideEither[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			// equals_deep.go
			"EqDeepT2": reflect.ValueOf(EqDeepT2[any]),
			"EqDeep":   reflect.ValueOf(EqDeep[any]),
			"EqDeepOp": reflect.ValueOf(EqDeepOp[any, any, any, any, any, any]),
			// error.go
			"OpticError": reflect.ValueOf(OpticError),
			"Error":      reflect.ValueOf(Error[any, any]),
			"ErrorI":     reflect.ValueOf(ErrorI[any, any, any]),
			"Throw":      reflect.ValueOf(Throw[any]),
			"ErrorP":     reflect.ValueOf(ErrorP[any, any, any, any]),
			"ErrorIP":    reflect.ValueOf(ErrorIP[any, any, any, any, any]),
			"ErrorIs":    reflect.ValueOf(ErrorIs),
			"ErrorAs":    reflect.ValueOf(ErrorAs[error]),
			"WithPanic":  reflect.ValueOf(WithPanic[any, any, any, any, any, any, any, any, any]),
			// exprhandler.go
			"ExprOptic": reflect.ValueOf(ExprOptic[any, any, any, any, any, any, any, any, any]),
			// field_lens.go
			//TODO: I think these will need some hand crafting
			"PtrFieldLens":  reflect.ValueOf(PtrFieldLens[any, any]),
			"PtrFieldLensE": reflect.ValueOf(PtrFieldLensE[any, any]),
			// getmod.go
			"GetMod":    reflect.ValueOf(GetMod[any, any]),
			"GetModP":   reflect.ValueOf(GetModP[any, any, any, any]),
			"GetModE":   reflect.ValueOf(GetModE[any, any]),
			"GetModEP":  reflect.ValueOf(GetModEP[any, any, any, any]),
			"GetModI":   reflect.ValueOf(GetModI[any, any, any]),
			"GetModIP":  reflect.ValueOf(GetModIP[any, any, any, any, any]),
			"GetModIE":  reflect.ValueOf(GetModIE[any, any, any]),
			"GetModIEP": reflect.ValueOf(GetModIEP[any, any, any, any, any]),
			// getter.go
			"Getter":   reflect.ValueOf(Getter[any, any]),
			"GetterE":  reflect.ValueOf(GetterE[any, any]),
			"GetterI":  reflect.ValueOf(GetterI[any, any, any]),
			"GetterIE": reflect.ValueOf(GetterIE[any, any, any]),
			// identity.go
			"Identity":    reflect.ValueOf(Identity[any]),
			"IdentityP":   reflect.ValueOf(IdentityP[any, any]),
			"IdentityI":   reflect.ValueOf(IdentityI[any, any, any]),
			"IdentityIP":  reflect.ValueOf(IdentityIP[any, any, any]),
			"Value":       reflect.ValueOf(Value[any]),
			"IgnoreWrite": reflect.ValueOf(IgnoreWrite[any, any, any, any, any, any, any, any, any]),
			"Const":       reflect.ValueOf(Const[any, any]),
			"ConstI":      reflect.ValueOf(ConstI[any, any, any, any]),
			"ConstIP":     reflect.ValueOf(ConstIP[any, any, any, any, any, any]),
			"Nothing":     reflect.ValueOf(Nothing[any, any]),
			"NothingI":    reflect.ValueOf(NothingI[any, any, any, any]),
			// iso.go
			"Involuted":  reflect.ValueOf(Involuted[any]),
			"InvolutedE": reflect.ValueOf(InvolutedE[any]),
			"Iso":        reflect.ValueOf(Iso[any, any]),
			"IsoE":       reflect.ValueOf(IsoE[any, any]),
			"IsoP":       reflect.ValueOf(IsoP[any, any, any, any]),
			"IsoEP":      reflect.ValueOf(IsoEP[any, any, any, any]),
			// iteration.go
			"Iteration":   reflect.ValueOf(Iteration[any, any]),
			"IterationE":  reflect.ValueOf(IterationE[any, any]),
			"IterationI":  reflect.ValueOf(IterationI[any, any, any]),
			"IterationIE": reflect.ValueOf(IterationIE[any, any, any]),
			// ixmatch.go
			"PredToIxMatch":     reflect.ValueOf(PredToIxMatch[any, any]),
			"AsIxMatchT2":       reflect.ValueOf(AsIxMatchT2[any, any, any, any, any, any, any, any, any]),
			"IxMatchVoid":       reflect.ValueOf(IxMatchVoid),
			"IxMatchComparable": reflect.ValueOf(IxMatchComparable[any]),
			"IxMatchDeep":       reflect.ValueOf(IxMatchDeep[any]),
			// laws.go
			"ValidateOptic":      reflect.ValueOf(ValidateOptic[any, any, any, any, any, any, any]),
			"ValidateOpticPred":  reflect.ValueOf(ValidateOpticPred[any, any, any, any, any, any, any, any]),
			"ValidateOpticP":     reflect.ValueOf(ValidateOpticP[any, any, any, any, any, any, any, any, any]),
			"ValidateOpticPredP": reflect.ValueOf(ValidateOpticPredP[any, any, any, any, any, any, any, any, any, any]),
			// lens.go
			"Lens":    reflect.ValueOf(Lens[any, any]),
			"LensP":   reflect.ValueOf(LensP[any, any, any, any]),
			"LensE":   reflect.ValueOf(LensE[any, any]),
			"LensEP":  reflect.ValueOf(LensEP[any, any, any, any]),
			"LensI":   reflect.ValueOf(LensI[any, any, any]),
			"LensIP":  reflect.ValueOf(LensIP[any, any, any, any, any]),
			"LensIE":  reflect.ValueOf(LensIE[any, any, any]),
			"LensIEP": reflect.ValueOf(LensIEP[any, any, any, any, any]),
			// logic.go
			"AndT2":   reflect.ValueOf(AndT2),
			"And":     reflect.ValueOf(And),
			"AndOp":   reflect.ValueOf(AndOp[any, any, any]),
			"OrT2":    reflect.ValueOf(OrT2),
			"Or":      reflect.ValueOf(Or),
			"OrOp":    reflect.ValueOf(OrOp[any, any, any]),
			"Not":     reflect.ValueOf(Not),
			"NotOp":   reflect.ValueOf(NotOp[any, any]),
			"Case":    reflect.ValueOf(Case[any, any, any, any, any, any, any, any, any, any]),
			"If":      reflect.ValueOf(If[any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Switch":  reflect.ValueOf(Switch[any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Switch2": reflect.ValueOf(Switch2[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Switch3": reflect.ValueOf(Switch3[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"Switch4": reflect.ValueOf(Switch4[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"SwitchN": reflect.ValueOf(SwitchN[any, any, any, any, any, any, any, any, any, any]),
			// makecolops.go
			"ColTypeOp":      reflect.ValueOf(ColTypeOp[any, any, any, any, any, any, any, any, any, any]),
			"DiffColTypeT2":  reflect.ValueOf(DiffColTypeT2[any, any, any, any, any]),
			"DiffColTypeT2I": reflect.ValueOf(DiffColTypeT2I[any, any, any, any, any]),
			// map.go
			"TraverseMap":   reflect.ValueOf(TraverseMap[any, any]),
			"TraverseMapP":  reflect.ValueOf(TraverseMapP[any, any, any]),
			"AtMap":         reflect.ValueOf(AtMap[any, any]),
			"AtMapT2":       reflect.ValueOf(AtMapT2[any, any]),
			"MapOf":         reflect.ValueOf(MapOf[any, any, any, any, any, any, any, any]),
			"MapOfReduced":  reflect.ValueOf(MapOfReduced[any, any, any, any, any, any, any, any, any, any]),
			"MapOfReducedP": reflect.ValueOf(MapOfReducedP[any, any, any, any, any, any, any, any, any, any, any]),
			"MapOfP":        reflect.ValueOf(MapOfP[any, any, any, any, any, any, any, any, any]),
			"MapToCol":      reflect.ValueOf(MapToCol[any, any]),
			"MapToColP":     reflect.ValueOf(MapToColP[any, any, any]),
			"MapColType":    reflect.ValueOf(MapColType[any, any]),
			"MapColTypeP":   reflect.ValueOf(MapColTypeP[any, any, any]),
			"MakeMap":       reflect.ValueOf(MakeMap[any, any, any]),
			// map_ops.go
			"MapCol":         reflect.ValueOf(MapCol[any, any]),
			"TraverseMapCol": reflect.ValueOf(TraverseMapCol[any, any]),
			"EqMap":          reflect.ValueOf(EqMap[any, any, any]),
			"EqMapT2":        reflect.ValueOf(EqMapT2[any, any, any]),
			"MapOp":          reflect.ValueOf(MapOp[any, any, any, any, any, any, any, any]),
			"ColToMap":       reflect.ValueOf(ColToMap[any, any]),
			"ColToMapP":      reflect.ValueOf(ColToMapP[any, any, any]),
			"DiffMap":        reflect.ValueOf(DiffMap[any, any, any, any]),
			"DiffMapI":       reflect.ValueOf(DiffMapI[any, any, any, any]),
			"FilteredMap":    reflect.ValueOf(FilteredMap[any, any, any]),
			"FilteredMapI":   reflect.ValueOf(FilteredMapI[any, any, any]),
			"AppendMap":      reflect.ValueOf(AppendMap[any, any, any]),
			// math.go
			"BinaryOp":     reflect.ValueOf(BinaryOp[any, any, any]),
			"BinaryOpE":    reflect.ValueOf(BinaryOpE[any, any, any]),
			"UnaryOp":      reflect.ValueOf(UnaryOp[any, any]),
			"OpT2IToOptic": reflect.ValueOf(OpT2IToOptic[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"OpT2ToOptic":  reflect.ValueOf(OpT2ToOptic[any, any, any, any, any, any, any, any, any, any, any, any]),
			"MulT2":        reflect.ValueOf(MulT2[float64]),
			"Mul":          reflect.ValueOf(Mul[float64]),
			"MulOp":        reflect.ValueOf(MulOp[any, float64, any, any, any, any]),
			"Product":      reflect.ValueOf(Product[float64]),
			"DivT2":        reflect.ValueOf(DivT2[float64]),
			"Div":          reflect.ValueOf(Div[float64]),
			"DivQuotient":  reflect.ValueOf(DivQuotient[float64]),
			"DivOp":        reflect.ValueOf(DivOp[any, float64, any, any, any, any]),
			"ModT2":        reflect.ValueOf(ModT2[int]),
			"Mod":          reflect.ValueOf(Mod[int]),
			"ModOp":        reflect.ValueOf(ModOp[any, int, any, any, any, any]),
			"AddT2":        reflect.ValueOf(AddT2[float64]),
			"Add":          reflect.ValueOf(Add[float64]),
			"AddOp":        reflect.ValueOf(AddOp[any, float64, any, any, any, any]),
			"Sum":          reflect.ValueOf(Sum[float64]),
			"SubT2":        reflect.ValueOf(SubT2[float64]),
			"Sub":          reflect.ValueOf(Sub[float64]),
			"SubFrom":      reflect.ValueOf(SubFrom[float64]),
			"SubOp":        reflect.ValueOf(SubOp[any, float64, any, any, any, any]),
			"PowT2":        reflect.ValueOf(PowT2),
			"Pow":          reflect.ValueOf(Pow),
			"PowOp":        reflect.ValueOf(PowOp[any, any, any, any, any]),
			"RootT2":       reflect.ValueOf(RootT2),
			"Root":         reflect.ValueOf(Root),
			"RootOp":       reflect.ValueOf(RootOp[any, any, any, any, any]),
			"Negate":       reflect.ValueOf(Negate[float64]),
			"Abs":          reflect.ValueOf(Abs[float64]),
			"ParseInt":     reflect.ValueOf(ParseInt[float64]),
			"FormatInt":    reflect.ValueOf(FormatInt[float64]),
			"ParseIntP":    reflect.ValueOf(ParseIntP[float64]),
			"ParseFloat":   reflect.ValueOf(ParseFloat[float64]),
			"ParseFloatP":  reflect.ValueOf(ParseFloatP[float64]),
			"FormatFloat":  reflect.ValueOf(FormatFloat[float64]),
			"Mean":         reflect.ValueOf(Mean[float64]),
			"Median":       reflect.ValueOf(Median[float64]),
			"Mode":         reflect.ValueOf(Mode[float64]),
			"MinT2":        reflect.ValueOf(MinT2[float64]),
			"Min":          reflect.ValueOf(Min[float64]),
			"MinOp":        reflect.ValueOf(MinOp[any, float64, any, any, any, any]),
			"MinReducer":   reflect.ValueOf(MinReducer[float64]),
			"MaxT2":        reflect.ValueOf(MaxT2[float64]),
			"Max":          reflect.ValueOf(Max[float64]),
			"MaxOp":        reflect.ValueOf(MaxOp[any, float64, any, any, any, any]),
			"MaxReducer":   reflect.ValueOf(MaxReducer[float64]),
			"Clamp":        reflect.ValueOf(Clamp[float64]),
			// method_lens.go
			"MethodGetter":        reflect.ValueOf(MethodGetter[any, any]),
			"MethodGetterI":       reflect.ValueOf(MethodGetterI[any, any, any]),
			"MethodGetterE":       reflect.ValueOf(MethodGetterE[any, any]),
			"MethodGetterContext": reflect.ValueOf(MethodGetterContext[any, any]),
			"MethodGetterIE":      reflect.ValueOf(MethodGetterIE[any, any, any]),
			"MethodLens":          reflect.ValueOf(MethodLens[any, any]),
			"MethodLensI":         reflect.ValueOf(MethodLensI[any, any, any]),
			"MethodLensP":         reflect.ValueOf(MethodLensP[any, any, any, any]),
			"MethodLensE":         reflect.ValueOf(MethodLensE[any, any]),
			"MethodLensContext":   reflect.ValueOf(MethodLensContext[any, any]),
			"MethodLensIEP":       reflect.ValueOf(MethodLensIEP[any, any, any, any, any]),
			// metrics.go
			"WithMetrics":     reflect.ValueOf(WithMetrics[any, any, any, any, any, any, any, any, any]),
			"IncCustomMetric": reflect.ValueOf(IncCustomMetric),
			// must.go
			"Must":   reflect.ValueOf(Must[any]),
			"Must2":  reflect.ValueOf(Must2[any, any]),
			"MustI":  reflect.ValueOf(MustI[any, any]),
			"Must2I": reflect.ValueOf(Must2I[any, any, any]),
			// omni.go
			"UnsafeOmni": reflect.ValueOf(UnsafeOmni[any, any, any, any, any, any, any, any, any]),
			"ExprDef":    reflect.ValueOf(ExprDef),
			"ExprCustom": reflect.ValueOf(ExprCustom),
			"ExprTODO":   reflect.ValueOf(ExprTODO),
			"Omni":       reflect.ValueOf(Omni[any, any, any, any, any, any, any, any, any]),
			// operator.go
			"Op":            reflect.ValueOf(Op[any, any]),
			"OpE":           reflect.ValueOf(OpE[any, any]),
			"OpI":           reflect.ValueOf(OpI[any, any, any]),
			"OpIE":          reflect.ValueOf(OpIE[any, any, any]),
			"OpT2":          reflect.ValueOf(OpT2[any, any, any]),
			"OpT2E":         reflect.ValueOf(OpT2E[any, any, any]),
			"OpT2I":         reflect.ValueOf(OpT2I[any, any, any, any, any]),
			"OpT2IE":        reflect.ValueOf(OpT2IE[any, any, any, any, any]),
			"Operator":      reflect.ValueOf(Operator[any, any]),
			"OperatorI":     reflect.ValueOf(OperatorI[any, any, any]),
			"OperatorE":     reflect.ValueOf(OperatorE[any, any]),
			"OperatorIE":    reflect.ValueOf(OperatorIE[any, any, any, any]),
			"OpToOpI":       reflect.ValueOf(OpToOpI[any, any, any, any, any]),
			"PredT2ToOpT2I": reflect.ValueOf(PredT2ToOpT2I[any, any, any, any, any]),
			"PredToOpI":     reflect.ValueOf(PredToOpI[any, any, any]),
			"OpT2ToOpT2I":   reflect.ValueOf(OpT2ToOpT2I[any, any, any, any, any]),
			"AsIxGet":       reflect.ValueOf(AsIxGet[any, any, any, any, any, any, any, any, any]),
			"OpOnIx":        reflect.ValueOf(OpOnIx[any, any, any, any, any]),
			"PredOnIx":      reflect.ValueOf(PredOnIx[any, any, any]),
			"OpT2Bind":      reflect.ValueOf(OpT2Bind[any, any, any, any, any]),
			"OpT2IsoBind":   reflect.ValueOf(OpT2IsoBind[any, any, any, any, any]),
			"OpToOptic":     reflect.ValueOf(OpToOptic[any, any, any, any]),
			"OpIToOptic":    reflect.ValueOf(OpIToOptic[any, any, any, any, any, any]),
			// option.go
			"Present":        reflect.ValueOf(Present[any]),
			"Some":           reflect.ValueOf(Some[any]),
			"SomeE":          reflect.ValueOf(SomeE[any]),
			"SomeP":          reflect.ValueOf(SomeP[any, any]),
			"SomeEP":         reflect.ValueOf(SomeEP[any, any]),
			"TraverseOption": reflect.ValueOf(TraverseOption[any]),
			"None":           reflect.ValueOf(None[any]),
			"Non":            reflect.ValueOf(Non[any, any]),
			"PtrOption":      reflect.ValueOf(PtrOption[any]),
			"PtrOptionP":     reflect.ValueOf(PtrOptionP[any, any]),
			// orderby.go
			"OrderByOp":   reflect.ValueOf(OrderByOp[any]),
			"OrderByOpE":  reflect.ValueOf(OrderByOpE[any]),
			"OrderByOpI":  reflect.ValueOf(OrderByOpI[any, any]),
			"OrderByOpIE": reflect.ValueOf(OrderByOpIE[any, any]),
			"Desc":        reflect.ValueOf(Desc[any, any]),
			"OrderByN":    reflect.ValueOf(OrderByN[any, any]),
			"OrderBy2":    reflect.ValueOf(OrderBy2[any, any, any]),
			"OrderBy3":    reflect.ValueOf(OrderBy3[any, any, any, any]),
			"OrderBy4":    reflect.ValueOf(OrderBy4[any, any, any, any, any]),
			"DescI":       reflect.ValueOf(DescI[any, any, any]),
			// pointer.go
			"TraversePtr":   reflect.ValueOf(TraversePtr[any]),
			"TraversePtrP":  reflect.ValueOf(TraversePtrP[any, any]),
			"TraversePtrE":  reflect.ValueOf(TraversePtrE[any]),
			"TraversePtrEP": reflect.ValueOf(TraversePtrEP[any, any]),
			// predicate.go
			"PredGet":       reflect.ValueOf(PredGet[any]),
			"True":          reflect.ValueOf(True[any]),
			"False":         reflect.ValueOf(False[any]),
			"Even":          reflect.ValueOf(Even[int]),
			"Odd":           reflect.ValueOf(Odd[int]),
			"GtT2":          reflect.ValueOf(GtT2[float64]),
			"Gt":            reflect.ValueOf(Gt[int]),
			"GtOp":          reflect.ValueOf(GtOp[any, float64, any, any, any, any]),
			"GteT2":         reflect.ValueOf(GteT2[float64]),
			"Gte":           reflect.ValueOf(Gte[float64]),
			"GteOp":         reflect.ValueOf(GteOp[any, float64, any, any, any, any]),
			"LtT2":          reflect.ValueOf(LtT2[float64]),
			"Lt":            reflect.ValueOf(Lt[float64]),
			"LtOp":          reflect.ValueOf(LtOp[any, float64, any, any, any, any]),
			"LteT2":         reflect.ValueOf(LteT2[float64]),
			"Lte":           reflect.ValueOf(Lte[float64]),
			"LteOp":         reflect.ValueOf(LteOp[any, float64, any, any, any, any]),
			"EqT2":          reflect.ValueOf(EqT2[any]),
			"Eq":            reflect.ValueOf(Eq[any]),
			"EqOp":          reflect.ValueOf(EqOp[any, any, any, any, any, any]),
			"PredT2ToOptic": reflect.ValueOf(PredT2ToOptic[any, any, any, any, any, any, any, any, any]),
			"InT2":          reflect.ValueOf(InT2[any]),
			"In":            reflect.ValueOf(In[any]),
			"NeT2":          reflect.ValueOf(NeT2[any]),
			"Ne":            reflect.ValueOf(Ne[any]),
			"NeOp":          reflect.ValueOf(NeOp[any, any, any, any, any, any]),
			"Any":           reflect.ValueOf(Any[any, any, any, any, any, any, any, any, any, any]),
			"Contains":      reflect.ValueOf(Contains[any, any, any, any, any, any, any, any, any]),
			"All":           reflect.ValueOf(All[any, any, any, any, any, any, any, any, any, any]),
			"NotEmpty":      reflect.ValueOf(NotEmpty[any, any, any, any, any, any, any, any, any]),
			"Empty":         reflect.ValueOf(Empty[any, any, any, any, any, any, any, any, any]),
			"PredToOptic":   reflect.ValueOf(PredToOptic[any, any]),
			"PredEToOptic":  reflect.ValueOf(PredEToOptic[any]),
			// predicate_indexed.go
			"PredGetI": reflect.ValueOf(PredGetI[any, any, any]),
			"EqI":      reflect.ValueOf(EqI[any, any]),
			"NeI":      reflect.ValueOf(NeI[any, any]),
			"GtI":      reflect.ValueOf(GtI[any, float64]),
			"GteI":     reflect.ValueOf(GteI[any, float64]),
			"LtI":      reflect.ValueOf(LtI[any, float64]),
			"LteI":     reflect.ValueOf(LteI[any, float64]),
			"AnyI":     reflect.ValueOf(AnyI[any, any, any, any, any, any, any, any, any, any]),
			"AllI":     reflect.ValueOf(AllI[any, any, any, any, any, any, any, any, any, any]),
			// prism.go
			"Prism":    reflect.ValueOf(Prism[any, any]),
			"PrismP":   reflect.ValueOf(PrismP[any, any, any, any]),
			"PrismE":   reflect.ValueOf(PrismE[any, any]),
			"PrismEP":  reflect.ValueOf(PrismEP[any, any, any, any]),
			"PrismI":   reflect.ValueOf(PrismI[any, any, any]),
			"PrismIP":  reflect.ValueOf(PrismIP[any, any, any, any, any]),
			"PrismIE":  reflect.ValueOf(PrismIE[any, any, any]),
			"PrismIEP": reflect.ValueOf(PrismIEP[any, any, any, any, any]),
			//TODO: I think I can make all these reconstraints no-op in he playground.
			// reconstrain.go
			"UnsafeReconstrain": reflect.ValueOf(UnsafeReconstrain[any, any, any, any, any, any, any, any, any, any, any, any, any]),
			// reconstrain_dir.go
			"Bd":        reflect.ValueOf(Bd[any, any, any, any, any, any, any, any, any]),
			"Ud":        reflect.ValueOf(Ud[any, any, any, any, any, any, any, any, any]),
			"DirL":      reflect.ValueOf(DirL[any, any, any, any, any, any, any, any, any, any]),
			"DirR":      reflect.ValueOf(DirR[any, any, any, any, any, any, any, any, any, any]),
			"DirSwap":   reflect.ValueOf(DirSwap[any, any, any, any, any, any, any, any, any, any]),
			"DirSwapL":  reflect.ValueOf(DirSwapL[any, any, any, any, any, any, any, any, any, any, any]),
			"DirSwapR":  reflect.ValueOf(DirSwapR[any, any, any, any, any, any, any, any, any, any, any]),
			"DirMerge":  reflect.ValueOf(DirMerge[any, any, any, any, any, any, any, any, any]),
			"DirMergeL": reflect.ValueOf(DirMergeL[any, any, any, any, any, any, any, any, any, any]),
			"DirMergeR": reflect.ValueOf(DirMergeR[any, any, any, any, any, any, any, any, any, any]),
			"DirTrans":  reflect.ValueOf(DirTrans[any, any, any, any, any, any, any, any, any, any, any, any]),
			"DirTransL": reflect.ValueOf(DirTransL[any, any, any, any, any, any, any, any, any, any, any]),
			"DirTransR": reflect.ValueOf(DirTransR[any, any, any, any, any, any, any, any, any, any, any]),
			// reconstrain_err.go
			"EPure":      reflect.ValueOf(EPure[any, any, any, any, any, any, any, any, any]),
			"EErr":       reflect.ValueOf(EErr[any, any, any, any, any, any, any, any, any]),
			"EErrL":      reflect.ValueOf(EErrL[any, any, any, any, any, any, any, any, any, any]),
			"EErrR":      reflect.ValueOf(EErrR[any, any, any, any, any, any, any, any, any, any]),
			"EErrSwap":   reflect.ValueOf(EErrSwap[any, any, any, any, any, any, any, any, any, any]),
			"EErrSwapL":  reflect.ValueOf(EErrSwapL[any, any, any, any, any, any, any, any, any, any, any]),
			"EErrSwapR":  reflect.ValueOf(EErrSwapR[any, any, any, any, any, any, any, any, any, any, any]),
			"EErrMerge":  reflect.ValueOf(EErrMerge[any, any, any, any, any, any, any, any, any]),
			"EErrMergeL": reflect.ValueOf(EErrMergeL[any, any, any, any, any, any, any, any, any, any]),
			"EErrMergeR": reflect.ValueOf(EErrMergeR[any, any, any, any, any, any, any, any, any, any]),
			"EErrTrans":  reflect.ValueOf(EErrTrans[any, any, any, any, any, any, any, any, any, any, any, any]),
			"EErrTransL": reflect.ValueOf(EErrTransL[any, any, any, any, any, any, any, any, any, any, any]),
			"EErrTransR": reflect.ValueOf(EErrTransR[any, any, any, any, any, any, any, any, any, any, any]),
			// reconstrain_ret.go
			"Ret1":      reflect.ValueOf(Ret1[any, any, any, any, any, any, any, any, any]),
			"RetM":      reflect.ValueOf(RetM[any, any, any, any, any, any, any, any, any]),
			"RetL":      reflect.ValueOf(RetL[any, any, any, any, any, any, any, any, any, any]),
			"RetR":      reflect.ValueOf(RetR[any, any, any, any, any, any, any, any, any, any]),
			"RetSwap":   reflect.ValueOf(RetSwap[any, any, any, any, any, any, any, any, any, any]),
			"RetSwapL":  reflect.ValueOf(RetSwapL[any, any, any, any, any, any, any, any, any, any, any]),
			"RetSwapR":  reflect.ValueOf(RetSwapR[any, any, any, any, any, any, any, any, any, any, any]),
			"RetMerge":  reflect.ValueOf(RetMerge[any, any, any, any, any, any, any, any, any]),
			"RetMergeL": reflect.ValueOf(RetMergeL[any, any, any, any, any, any, any, any, any, any]),
			"RetMergeR": reflect.ValueOf(RetMergeR[any, any, any, any, any, any, any, any, any, any]),
			"RetTrans":  reflect.ValueOf(RetTrans[any, any, any, any, any, any, any, any, any, any, any, any]),
			"RetTransL": reflect.ValueOf(RetTransL[any, any, any, any, any, any, any, any, any, any, any]),
			"RetTransR": reflect.ValueOf(RetTransR[any, any, any, any, any, any, any, any, any, any, any]),
			// reconstrain_rw.go
			"Ro":       reflect.ValueOf(Ro[any, any, any, any, any, any, any, any, any]),
			"Rw":       reflect.ValueOf(Rw[any, any, any, any, any, any, any, any, any]),
			"RwL":      reflect.ValueOf(RwL[any, any, any, any, any, any, any, any, any, any]),
			"RwR":      reflect.ValueOf(RwR[any, any, any, any, any, any, any, any, any, any]),
			"RwSwap":   reflect.ValueOf(RwSwap[any, any, any, any, any, any, any, any, any, any]),
			"RwSwapL":  reflect.ValueOf(RwSwapL[any, any, any, any, any, any, any, any, any, any, any]),
			"RwSwapR":  reflect.ValueOf(RwSwapR[any, any, any, any, any, any, any, any, any, any, any]),
			"RwMerge":  reflect.ValueOf(RwMerge[any, any, any, any, any, any, any, any, any]),
			"RwMergeL": reflect.ValueOf(RwMergeL[any, any, any, any, any, any, any, any, any, any]),
			"RwMergeR": reflect.ValueOf(RwMergeR[any, any, any, any, any, any, any, any, any, any]),
			"RwTrans":  reflect.ValueOf(RwTrans[any, any, any, any, any, any, any, any, any, any, any, any]),
			"RwTransL": reflect.ValueOf(RwTransL[any, any, any, any, any, any, any, any, any, any, any]),
			"RwTransR": reflect.ValueOf(RwTransR[any, any, any, any, any, any, any, any, any, any, any]),
			// reducer.go
			"Reducer":           reflect.ValueOf(Reducer[any]),
			"ReducerP":          reflect.ValueOf(ReducerP[any, any, any]),
			"ReducerE":          reflect.ValueOf(ReducerE[any]),
			"ReducerEP":         reflect.ValueOf(ReducerEP[any, any, any]),
			"CombiReducer":      reflect.ValueOf(CombiReducer[any, any, any, any]),
			"ReducerExprDef":    reflect.ValueOf(ReducerExprDef),
			"ReducerExprCustom": reflect.ValueOf(ReducerExprCustom),
			"ReducerExprTODO":   reflect.ValueOf(ReducerExprTODO),
			"AsReducer":         reflect.ValueOf(AsReducer[any, any, any, any]),
			"AsReducerP":        reflect.ValueOf(AsReducerP[any, any, any, any, any, any, any, any, any]),
			"ReducerT2":         reflect.ValueOf(ReducerT2[any, any, any, any, any, any, any, any]),
			"ReducerT3":         reflect.ValueOf(ReducerT3[any, any, any, any, any, any, any, any, any, any, any, any]),
			"FirstReducer":      reflect.ValueOf(FirstReducer[any]),
			"LastReducer":       reflect.ValueOf(LastReducer[any]),
			// seq.go
			"PullI":    reflect.ValueOf(PullI[any, any]),
			"PullE":    reflect.ValueOf(PullE[any, any]),
			"PullIE":   reflect.ValueOf(PullIE[any, any]),
			"SeqOf":    reflect.ValueOf(SeqOf[any, any, any, any, any, any, any, any]),
			"SeqOfP":   reflect.ValueOf(SeqOfP[any, any, any, any, any, any, any, any, any]),
			"SeqIOf":   reflect.ValueOf(SeqIOf[any, any, any, any, any, any, any, any]),
			"SeqIOfP":  reflect.ValueOf(SeqIOfP[any, any, any, any, any, any, any, any, any]),
			"SeqEOf":   reflect.ValueOf(SeqEOf[any, any, any, any, any, any, any, any]),
			"SeqEOfP":  reflect.ValueOf(SeqEOfP[any, any, any, any, any, any, any, any, any]),
			"SeqIEOf":  reflect.ValueOf(SeqIEOf[any, any, any, any, any, any, any, any]),
			"SeqIEOfP": reflect.ValueOf(SeqIEOfP[any, any, any, any, any, any, any, any, any]),
			// slice.go
			"TraverseSlice":      reflect.ValueOf(TraverseSlice[any]),
			"TraverseSliceP":     reflect.ValueOf(TraverseSliceP[any, any]),
			"AtSlice":            reflect.ValueOf(AtSlice[any, any]),
			"AtSliceT2":          reflect.ValueOf(AtSliceT2[any, any]),
			"SliceOf":            reflect.ValueOf(SliceOf[any, any, any, any, any, any, any, any]),
			"SliceOfP":           reflect.ValueOf(SliceOfP[any, any, any, any, any, any, any, any, any]),
			"SliceToCol":         reflect.ValueOf(SliceToCol[any]),
			"SliceToColP":        reflect.ValueOf(SliceToColP[any, any]),
			"SliceColType":       reflect.ValueOf(SliceColType[any]),
			"SliceColTypeP":      reflect.ValueOf(SliceColTypeP[any, any]),
			"AppendSliceReducer": reflect.ValueOf(AppendSliceReducer[any]),
			"SliceTail":          reflect.ValueOf(SliceTail[any]),
			"MakeSlice":          reflect.ValueOf(MakeSlice[any, any]),
			// slice_ops.go
			"SliceCol":         reflect.ValueOf(SliceCol[any]),
			"TraverseSliceCol": reflect.ValueOf(TraverseSliceCol[any]),
			"EqSlice":          reflect.ValueOf(EqSlice[any, any]),
			"EqSliceT2":        reflect.ValueOf(EqSliceT2[any, any]),
			"SliceOp":          reflect.ValueOf(SliceOp[any, any, any, any, any, any, any]),
			"ColToSlice":       reflect.ValueOf(ColToSlice[any]),
			"ColToSliceP":      reflect.ValueOf(ColToSliceP[any, any]),
			"DiffSlice":        reflect.ValueOf(DiffSlice[any, any, any]),
			"DiffSliceI":       reflect.ValueOf(DiffSliceI[any, any, any]),
			"FilteredSlice":    reflect.ValueOf(FilteredSlice[any, any]),
			"FilteredSliceI":   reflect.ValueOf(FilteredSliceI[any, any]),
			"AppendSlice":      reflect.ValueOf(AppendSlice[any, any]),
			"PrependSlice":     reflect.ValueOf(PrependSlice[any, any]),
			"SubSlice":         reflect.ValueOf(SubSlice[any]),
			"ReversedSlice":    reflect.ValueOf(ReversedSlice[any]),
			"OrderedSlice":     reflect.ValueOf(OrderedSlice[any, any]),
			"OrderedSliceI":    reflect.ValueOf(OrderedSliceI[any, any]),
			// string.go
			"TraverseString":       reflect.ValueOf(TraverseString),
			"TraverseStringP":      reflect.ValueOf(TraverseStringP[string, rune]),
			"MatchIndexOffsets":    reflect.ValueOf(MatchIndexOffsets),
			"MatchIndexCaptures":   reflect.ValueOf(MatchIndexCaptures),
			"MatchString":          reflect.ValueOf(MatchString),
			"CaptureMapString":     reflect.ValueOf(CaptureMapString),
			"CaptureString":        reflect.ValueOf(CaptureString),
			"SplitString":          reflect.ValueOf(SplitString),
			"Worded":               reflect.ValueOf(Worded),
			"Lined":                reflect.ValueOf(Lined),
			"StringToCol":          reflect.ValueOf(StringToCol),
			"EncodeString":         reflect.ValueOf(EncodeString),
			"StringColType":        reflect.ValueOf(StringColType),
			"StringHasPrefix":      reflect.ValueOf(StringHasPrefix),
			"StringHasSuffix":      reflect.ValueOf(StringHasSuffix),
			"StringBuilderReducer": reflect.ValueOf(StringBuilderReducer),
			"StringOf":             reflect.ValueOf(StringOf[any, any, any, any, any, any, any]),
			// string_ops.go
			"StringCol":         reflect.ValueOf(StringCol),
			"TraverseStringCol": reflect.ValueOf(TraverseStringCol),
			"EqString":          reflect.ValueOf(EqString),
			"EqStringT2":        reflect.ValueOf(EqStringT2),
			"StringOp":          reflect.ValueOf(StringOp[any, any, any, any, any]),
			"ColToString":       reflect.ValueOf(ColToString),
			"ColToStringP":      reflect.ValueOf(ColToStringP),
			"DiffString":        reflect.ValueOf(DiffString[any, any]),
			"DiffStringI":       reflect.ValueOf(DiffStringI[any, any]),
			"FilteredString":    reflect.ValueOf(FilteredString[any]),
			"FilteredStringI":   reflect.ValueOf(FilteredStringI[any]),
			"AppendString":      reflect.ValueOf(AppendString[any]),
			"PrependString":     reflect.ValueOf(PrependString[any]),
			"SubString":         reflect.ValueOf(SubString),
			"ReversedString":    reflect.ValueOf(ReversedString),
			"OrderedString":     reflect.ValueOf(OrderedString[any]),
			"OrderedStringI":    reflect.ValueOf(OrderedStringI[any]),
			// traversal.go
			"Traversal":    reflect.ValueOf(Traversal[any, any]),
			"TraversalP":   reflect.ValueOf(TraversalP[any, any, any, any]),
			"TraversalE":   reflect.ValueOf(TraversalE[any, any]),
			"TraversalEP":  reflect.ValueOf(TraversalEP[any, any, any, any]),
			"TraversalI":   reflect.ValueOf(TraversalI[any, any, any]),
			"TraversalIP":  reflect.ValueOf(TraversalIP[any, any, any, any, any]),
			"TraversalIE":  reflect.ValueOf(TraversalIE[any, any, any]),
			"TraversalIEP": reflect.ValueOf(TraversalIEP[any, any, any, any, any]),
			// tuple.go
			"SwappedT2": reflect.ValueOf(SwappedT2[any, any]),
			"BesideT2":  reflect.ValueOf(BesideT2[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			// tuple_generated.go
			"TraverseT2":  reflect.ValueOf(TraverseT2[any]),
			"TraverseT2P": reflect.ValueOf(TraverseT2P[any, any]),
			"TraverseT3":  reflect.ValueOf(TraverseT3[any]),
			"TraverseT3P": reflect.ValueOf(TraverseT3P[any, any]),
			"TraverseT4":  reflect.ValueOf(TraverseT4[any]),
			"TraverseT4P": reflect.ValueOf(TraverseT4P[any, any]),
			"TraverseT5":  reflect.ValueOf(TraverseT5[any]),
			"TraverseT5P": reflect.ValueOf(TraverseT5P[any, any]),
			"TraverseT6":  reflect.ValueOf(TraverseT6[any]),
			"TraverseT6P": reflect.ValueOf(TraverseT6P[any, any]),
			"TraverseT7":  reflect.ValueOf(TraverseT7[any]),
			"TraverseT7P": reflect.ValueOf(TraverseT7P[any, any]),
			"TraverseT8":  reflect.ValueOf(TraverseT8[any]),
			"TraverseT8P": reflect.ValueOf(TraverseT8P[any, any]),
			"TraverseT9":  reflect.ValueOf(TraverseT9[any]),
			"TraverseT9P": reflect.ValueOf(TraverseT9P[any, any]),
			"DupT2":       reflect.ValueOf(DupT2[any]),
			"DupT2P":      reflect.ValueOf(DupT2P[any, any]),
			"DupT3":       reflect.ValueOf(DupT3[any]),
			"DupT3P":      reflect.ValueOf(DupT3P[any, any]),
			"DupT4":       reflect.ValueOf(DupT4[any]),
			"DupT4P":      reflect.ValueOf(DupT4P[any, any]),
			"DupT5":       reflect.ValueOf(DupT5[any]),
			"DupT5P":      reflect.ValueOf(DupT5P[any, any]),
			"DupT6":       reflect.ValueOf(DupT6[any]),
			"DupT6P":      reflect.ValueOf(DupT6P[any, any]),
			"DupT7":       reflect.ValueOf(DupT7[any]),
			"DupT7P":      reflect.ValueOf(DupT7P[any, any]),
			"DupT8":       reflect.ValueOf(DupT8[any]),
			"DupT8P":      reflect.ValueOf(DupT8P[any, any]),
			"DupT9":       reflect.ValueOf(DupT9[any]),
			"DupT9P":      reflect.ValueOf(DupT9P[any, any]),
			"T2A":         reflect.ValueOf(T2A[any, any]),
			"T2AP":        reflect.ValueOf(T2AP[any, any, any]),
			"T2B":         reflect.ValueOf(T2B[any, any]),
			"T2BP":        reflect.ValueOf(T2BP[any, any, any]),
			"T3A":         reflect.ValueOf(T3A[any, any, any]),
			"T3AP":        reflect.ValueOf(T3AP[any, any, any, any]),
			"T3B":         reflect.ValueOf(T3B[any, any, any]),
			"T3BP":        reflect.ValueOf(T3BP[any, any, any, any]),
			"T3C":         reflect.ValueOf(T3C[any, any, any]),
			"T3CP":        reflect.ValueOf(T3CP[any, any, any, any]),
			"T4A":         reflect.ValueOf(T4A[any, any, any, any]),
			"T4AP":        reflect.ValueOf(T4AP[any, any, any, any, any]),
			"T4B":         reflect.ValueOf(T4B[any, any, any, any]),
			"T4BP":        reflect.ValueOf(T4BP[any, any, any, any, any]),
			"T4C":         reflect.ValueOf(T4C[any, any, any, any]),
			"T4CP":        reflect.ValueOf(T4CP[any, any, any, any, any]),
			"T4D":         reflect.ValueOf(T4D[any, any, any, any]),
			"T4DP":        reflect.ValueOf(T4DP[any, any, any, any, any]),
			"T5A":         reflect.ValueOf(T5A[any, any, any, any, any]),
			"T5AP":        reflect.ValueOf(T5AP[any, any, any, any, any, any]),
			"T5B":         reflect.ValueOf(T5B[any, any, any, any, any]),
			"T5BP":        reflect.ValueOf(T5BP[any, any, any, any, any, any]),
			"T5C":         reflect.ValueOf(T5C[any, any, any, any, any]),
			"T5CP":        reflect.ValueOf(T5CP[any, any, any, any, any, any]),
			"T5D":         reflect.ValueOf(T5D[any, any, any, any, any]),
			"T5DP":        reflect.ValueOf(T5DP[any, any, any, any, any, any]),
			"T5E":         reflect.ValueOf(T5E[any, any, any, any, any]),
			"T5EP":        reflect.ValueOf(T5EP[any, any, any, any, any, any]),
			"T6A":         reflect.ValueOf(T6A[any, any, any, any, any, any]),
			"T6AP":        reflect.ValueOf(T6AP[any, any, any, any, any, any, any]),
			"T6B":         reflect.ValueOf(T6B[any, any, any, any, any, any]),
			"T6BP":        reflect.ValueOf(T6BP[any, any, any, any, any, any, any]),
			"T6C":         reflect.ValueOf(T6C[any, any, any, any, any, any]),
			"T6CP":        reflect.ValueOf(T6CP[any, any, any, any, any, any, any]),
			"T6D":         reflect.ValueOf(T6D[any, any, any, any, any, any]),
			"T6DP":        reflect.ValueOf(T6DP[any, any, any, any, any, any, any]),
			"T6E":         reflect.ValueOf(T6E[any, any, any, any, any, any]),
			"T6EP":        reflect.ValueOf(T6EP[any, any, any, any, any, any, any]),
			"T6F":         reflect.ValueOf(T6F[any, any, any, any, any, any]),
			"T6FP":        reflect.ValueOf(T6FP[any, any, any, any, any, any, any]),
			"T7A":         reflect.ValueOf(T7A[any, any, any, any, any, any, any]),
			"T7AP":        reflect.ValueOf(T7AP[any, any, any, any, any, any, any, any]),
			"T7B":         reflect.ValueOf(T7B[any, any, any, any, any, any, any]),
			"T7BP":        reflect.ValueOf(T7BP[any, any, any, any, any, any, any, any]),
			"T7C":         reflect.ValueOf(T7C[any, any, any, any, any, any, any]),
			"T7CP":        reflect.ValueOf(T7CP[any, any, any, any, any, any, any, any]),
			"T7D":         reflect.ValueOf(T7D[any, any, any, any, any, any, any]),
			"T7DP":        reflect.ValueOf(T7DP[any, any, any, any, any, any, any, any]),
			"T7E":         reflect.ValueOf(T7E[any, any, any, any, any, any, any]),
			"T7EP":        reflect.ValueOf(T7EP[any, any, any, any, any, any, any, any]),
			"T7F":         reflect.ValueOf(T7F[any, any, any, any, any, any, any]),
			"T7FP":        reflect.ValueOf(T7FP[any, any, any, any, any, any, any, any]),
			"T7G":         reflect.ValueOf(T7G[any, any, any, any, any, any, any]),
			"T7GP":        reflect.ValueOf(T7GP[any, any, any, any, any, any, any, any]),
			"T8A":         reflect.ValueOf(T8A[any, any, any, any, any, any, any, any]),
			"T8AP":        reflect.ValueOf(T8AP[any, any, any, any, any, any, any, any, any]),
			"T8B":         reflect.ValueOf(T8B[any, any, any, any, any, any, any, any]),
			"T8BP":        reflect.ValueOf(T8BP[any, any, any, any, any, any, any, any, any]),
			"T8C":         reflect.ValueOf(T8C[any, any, any, any, any, any, any, any]),
			"T8CP":        reflect.ValueOf(T8CP[any, any, any, any, any, any, any, any, any]),
			"T8D":         reflect.ValueOf(T8D[any, any, any, any, any, any, any, any]),
			"T8DP":        reflect.ValueOf(T8DP[any, any, any, any, any, any, any, any, any]),
			"T8E":         reflect.ValueOf(T8E[any, any, any, any, any, any, any, any]),
			"T8EP":        reflect.ValueOf(T8EP[any, any, any, any, any, any, any, any, any]),
			"T8F":         reflect.ValueOf(T8F[any, any, any, any, any, any, any, any]),
			"T8FP":        reflect.ValueOf(T8FP[any, any, any, any, any, any, any, any, any]),
			"T8G":         reflect.ValueOf(T8G[any, any, any, any, any, any, any, any]),
			"T8GP":        reflect.ValueOf(T8GP[any, any, any, any, any, any, any, any, any]),
			"T8H":         reflect.ValueOf(T8H[any, any, any, any, any, any, any, any]),
			"T8HP":        reflect.ValueOf(T8HP[any, any, any, any, any, any, any, any, any]),
			"T9A":         reflect.ValueOf(T9A[any, any, any, any, any, any, any, any, any]),
			"T9AP":        reflect.ValueOf(T9AP[any, any, any, any, any, any, any, any, any, any]),
			"T9B":         reflect.ValueOf(T9B[any, any, any, any, any, any, any, any, any]),
			"T9BP":        reflect.ValueOf(T9BP[any, any, any, any, any, any, any, any, any, any]),
			"T9C":         reflect.ValueOf(T9C[any, any, any, any, any, any, any, any, any]),
			"T9CP":        reflect.ValueOf(T9CP[any, any, any, any, any, any, any, any, any, any]),
			"T9D":         reflect.ValueOf(T9D[any, any, any, any, any, any, any, any, any]),
			"T9DP":        reflect.ValueOf(T9DP[any, any, any, any, any, any, any, any, any, any]),
			"T9E":         reflect.ValueOf(T9E[any, any, any, any, any, any, any, any, any]),
			"T9EP":        reflect.ValueOf(T9EP[any, any, any, any, any, any, any, any, any, any]),
			"T9F":         reflect.ValueOf(T9F[any, any, any, any, any, any, any, any, any]),
			"T9FP":        reflect.ValueOf(T9FP[any, any, any, any, any, any, any, any, any, any]),
			"T9G":         reflect.ValueOf(T9G[any, any, any, any, any, any, any, any, any]),
			"T9GP":        reflect.ValueOf(T9GP[any, any, any, any, any, any, any, any, any, any]),
			"T9H":         reflect.ValueOf(T9H[any, any, any, any, any, any, any, any, any]),
			"T9HP":        reflect.ValueOf(T9HP[any, any, any, any, any, any, any, any, any, any]),
			"T9I":         reflect.ValueOf(T9I[any, any, any, any, any, any, any, any, any]),
			"T9IP":        reflect.ValueOf(T9IP[any, any, any, any, any, any, any, any, any, any]),
			"T2ToCol":     reflect.ValueOf(T2ToCol[any]),
			"T2ToColP":    reflect.ValueOf(T2ToColP[any, any]),
			"T3ToCol":     reflect.ValueOf(T3ToCol[any]),
			"T3ToColP":    reflect.ValueOf(T3ToColP[any, any]),
			"T4ToCol":     reflect.ValueOf(T4ToCol[any]),
			"T4ToColP":    reflect.ValueOf(T4ToColP[any, any]),
			"T5ToCol":     reflect.ValueOf(T5ToCol[any]),
			"T5ToColP":    reflect.ValueOf(T5ToColP[any, any]),
			"T6ToCol":     reflect.ValueOf(T6ToCol[any]),
			"T6ToColP":    reflect.ValueOf(T6ToColP[any, any]),
			"T7ToCol":     reflect.ValueOf(T7ToCol[any]),
			"T7ToColP":    reflect.ValueOf(T7ToColP[any, any]),
			"T8ToCol":     reflect.ValueOf(T8ToCol[any]),
			"T8ToColP":    reflect.ValueOf(T8ToColP[any, any]),
			"T9ToCol":     reflect.ValueOf(T9ToCol[any]),
			"T9ToColP":    reflect.ValueOf(T9ToColP[any, any]),
			"T2ColType":   reflect.ValueOf(T2ColType[any]),
			"T2ColTypeP":  reflect.ValueOf(T2ColTypeP[any, any]),
			"T3ColType":   reflect.ValueOf(T3ColType[any]),
			"T3ColTypeP":  reflect.ValueOf(T3ColTypeP[any, any]),
			"T4ColType":   reflect.ValueOf(T4ColType[any]),
			"T4ColTypeP":  reflect.ValueOf(T4ColTypeP[any, any]),
			"T5ColType":   reflect.ValueOf(T5ColType[any]),
			"T5ColTypeP":  reflect.ValueOf(T5ColTypeP[any, any]),
			"T6ColType":   reflect.ValueOf(T6ColType[any]),
			"T6ColTypeP":  reflect.ValueOf(T6ColTypeP[any, any]),
			"T7ColType":   reflect.ValueOf(T7ColType[any]),
			"T7ColTypeP":  reflect.ValueOf(T7ColTypeP[any, any]),
			"T8ColType":   reflect.ValueOf(T8ColType[any]),
			"T8ColTypeP":  reflect.ValueOf(T8ColTypeP[any, any]),
			"T9ColType":   reflect.ValueOf(T9ColType[any]),
			"T9ColTypeP":  reflect.ValueOf(T9ColTypeP[any, any]),
			"T2Of":        reflect.ValueOf(T2Of[any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"T3Of":        reflect.ValueOf(T3Of[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"T4Of":        reflect.ValueOf(T4Of[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"T5Of":        reflect.ValueOf(T5Of[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"T6Of":        reflect.ValueOf(T6Of[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"T7Of":        reflect.ValueOf(T7Of[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"T8Of":        reflect.ValueOf(T8Of[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"T9Of":        reflect.ValueOf(T9Of[any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]),
			"DelveT2":     reflect.ValueOf(DelveT2[any, any, any, any, any, any, any]),
			"DelveT3":     reflect.ValueOf(DelveT3[any, any, any, any, any, any, any]),
			"DelveT4":     reflect.ValueOf(DelveT4[any, any, any, any, any, any, any]),
			"DelveT5":     reflect.ValueOf(DelveT5[any, any, any, any, any, any, any]),
			"DelveT6":     reflect.ValueOf(DelveT6[any, any, any, any, any, any, any]),
			"DelveT7":     reflect.ValueOf(DelveT7[any, any, any, any, any, any, any]),
			"DelveT8":     reflect.ValueOf(DelveT8[any, any, any, any, any, any, any]),
			"DelveT9":     reflect.ValueOf(DelveT9[any, any, any, any, any, any, any]),
			// value.go
			"ValI":         reflect.ValueOf(ValI[any, any]),
			"ValE":         reflect.ValueOf(ValE[any]),
			"ValIE":        reflect.ValueOf(ValIE[any, any]),
			"ValueIValue":  reflect.ValueOf(ValueIValue[any, any]),
			"ValueIIndex":  reflect.ValueOf(ValueIIndex[any, any]),
			"ValueEValue":  reflect.ValueOf(ValueEValue[any]),
			"ValueEError":  reflect.ValueOf(ValueEError[any]),
			"ValueIEValue": reflect.ValueOf(ValueIEValue[any, any]),
			"ValueIEIndex": reflect.ValueOf(ValueIEIndex[any, any]),
			"ValueIEError": reflect.ValueOf(ValueIEError[any, any]),
			// variables.go
			"WithVar": reflect.ValueOf(WithVar[any, any, any, any, any, any, any, any, any, any, any, any]),
			"Var":     reflect.ValueOf(Var[any, any]),
		},
		ExportedTypes: map[string]reflect.Type{
			"Metrics": reflect.TypeFor[Metrics](),
			"Void":    reflect.TypeFor[Void](),
		},
	}

	goscript.RegisterPackage(&pkg)

	exprPkg := goscript.Package{
		Name: "github.com/spearson78/go-optic/expr",
		Exported: map[string]reflect.Value{
			"NewOpticTypeExpr": reflect.ValueOf(expr.NewOpticTypeExpr[any, any, any, any, any, any, any, any, any]),
		},
		ExportedTypes: map[string]reflect.Type{
			"Compose":  reflect.TypeFor[expr.Compose](),
			"Traverse": reflect.TypeFor[expr.Traverse](),
			"ParseInt": reflect.TypeFor[expr.ParseInt](),
		},
	}

	goscript.RegisterPackage(&exprPkg)
}
